# [ Server Configuration ]
server:
  port: 3000
  servlet:
    encoding:
      charset: "UTF-8"

  error:
    whitelabel:
      enabled: true
    include-message: always
    include-exception: true
    include-stacktrace: always
    include-binding-errors: always

  ssl:
    enabled: false
    key-store: "classpath:sslkey/hwpctrl_new_server.jks"
    key-store-password: "aims1234"
    key-password: "aims1234"
    key-alias: "aims"

# [ Server Configuration ]
spring:
  devtools:
    livereload:
      enabled: true
  mssql:
    datasource:
      driver-class-name: "net.sf.log4jdbc.sql.jdbcapi.DriverSpy"
      jdbc-url: "jdbc:log4jdbc:sqlserver://34.64.77.16:1433;DatabaseName=AIMS;"
      # jdbc_url: "jdbc:sqlserver://34.64.77.16:1433;databaseName=AIMS;"
      username: "aims3"
      password: "wnwospt001!"
      schema: "dbo"
    mapper:
      prefix: "APPR"

# [ KISA Crypto(Seed) Key ]
enc:
  seed:
    encKey: "45131c4cd4b505fd7533f9a131fc7a3cf85231bc6e88deac8df70e47f50b99db"
    vecKey: "01c0e5e3a439f0bf4ae6ab73ff44a21fb07d57cd739678e82cb769a04efe46aa"
    offset: 0

# [ Logback Configuration ]
logging:
  config: "classpath:logback-spring.xml"
